export const BASE_URL = 'https://bio-up-backend-chi.vercel.app/';
export const AUTH_ENDPOINT = BASE_URL+'auth';
export const COMPOSTS_ENDPOINT = BASE_URL+'composts';
export const PRODUCTS_ENDPOINT = BASE_URL+'products';
export const SERVICES_ENDPOINT = BASE_URL+'services';
export const COMMANDS_ENDPOINT = BASE_URL+'commands';
export const RATINGS_ENDPOINT = BASE_URL+'rating';
export const CONTRACT_ENDPOINT= BASE_URL+'contract';
export const SHIPMENT_ENDPOINT=BASE_URL+'shipment';
